config/routes.rb
Rails.application.routes.draw do
  # verb(get or post) 'path', to: "controller#action"
  root to: "pages#home"
  get 'pricing', to: "pages#pricing"
  get 'about', to: "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def pricing
    @prices = ['10', '20', '30']
    if params[:price] == "amazing"
      @prices = ['10', '20', '30']
    else
      @prices = ['5', '10', '20']
    end
  end

  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My first rails app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>navbar</h1>
    <%= yield %>
    <p>footer</p>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about.html.erb</h1>


<%= link_to "Back Home", root_path %>

app/views/pages/home.html.erb
<h1>Welcome to your rails app</h1>

<p>home.html.erb</p>

<%= link_to "Check out our prices", pricing_path  %>
<%= link_to "About us", about_path %>

app/views/pages/pricing.html.erb
<h1>Pricing Page</h1>

<h2>Subscribe Now</h2>

<ul>
  <% @prices.each do |price| %>
    <li><%= price %> Euros</li>
  <% end %>
</ul>


<h1>Tell us what you think</h1>
<form action="/pricing" method="get">
  <input type="text" name="price" placeholder="What do you think about our prices?">
  <input type="text" name="rating" placeholder="How do you rate our price?">
  <input type="submit">
</form>

<%= link_to "Back Home", root_path %>